version: '3.8'

services: 
  app:
    build: .
    command: python3 server.py
    volumes: 
       - .:/app
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=darla
      - POSTGRES_PASSWORD=mys3cretpassw0rd!
      - POSTGRES_DB=recipes
      - PGUSER=postgres
    user: postgres
    tty: true
    ports:
      - "5437:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql_scripts:/var/lib/postgresql/sql_scripts

volumes:
    pgdata:
  